name : Basic CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run CI message
        run: echo "CI pipline is running"
        run: [ -f "README.md "] && echo "File exists" || echo "File does not exist"
