name : Basic CI

on:
  push: 
    branches: [main]
  pull request:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI message
        run: |
          echo "CI pipline is running"
          if [ -f "README.md" ]; then
            echo "File exists" 
          else
            echo "File does not exist"
            exit 1 
          fi  
